---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: devops
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: test
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      tier: backend
  template:
    metadata:
      labels:
        app: test
        tier: backend
    spec:
      containers:
      - name: test
        image: 10.103.133.104:5000/test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
